# Generated by Django 4.1.7 on 2023-11-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
