# Generated by Django 4.2.7 on 2023-11-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pointhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointHistory',
        ),
    ]
