# Generated by Django 4.1.7 on 2023-11-11 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="accounts\\images\x08adge"
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="accounts\\images\\item"
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        blank=True, related_name="item", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
