# Generated by Django 4.1.7 on 2023-11-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_badge_image_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=100),
        ),
    ]
